### ISSUE TITLE
Cannot install Agama on my Apple Silicon Monterey

### ISSUE THREAD

**Issue by brugalada** [GalacticDynamics-Oxford/Agama#23] opened 2022-04-18 14:52 UTC
I am not sure if this has been asked before (could not find it) but I am having problems installing Agama on the new Apple M1 chips. I will try to solve it myself but thought better to report it here so that anyone can find it.

First of all, I created a conda environment with python 3.9. Then, I run `python setup.py install --user --yes` on the terminal and it failed. Here is the relevant part of the log:

> ==== Checking supported compiler options and available libraries ====
>c++ -fPIC -Wall -O2 test.cpp -o test.out 
>c++ -fPIC -Wall -O2 test.cpp -o test.out -fopenmp -Werror -Wno-unknown-pragmas
>clang: error: unsupported option '-fopenmp'
>clang: error: unsupported option '-fopenmp'
>c++ -fPIC -Wall -O2 test.cpp -o test.out -lgomp -Xpreprocessor -fopenmp -Werror -Wno-unknown-pragmas
>test.cpp:1:10: fatal error: 'omp.h' file not found
>#include <omp.h>
 >        ^~~~~~~
>1 error generated.
>c++ -fPIC -Wall -O2 test.cpp -o test.out -lomp -Xpreprocessor -fopenmp -Werror -Wno-unknown-pragmas
>test.cpp:1:10: fatal error: 'omp.h' file not found
>#include <omp.h>
>         ^~~~~~~
>1 error generated.
>Warning, OpenMP is not supported
If you're compiling on MacOS with clang, you'd better install another compiler such as GCC
Do you want to continue without OpenMP? [Y/N] y
c++ -fPIC -Wall -O2 test.cpp -o test.out -std=c++11
c++ -fPIC -Wall -O2 -std=c++11 test.cpp -o test.out -march=native
clang: error: the clang compiler does not support '-march=native'
c++ -fPIC -Wall -O2 -std=c++11 test.cpp -o test.out -march=core2
clang: error: the clang compiler does not support '-march=core2'
c++ -fPIC -Wall -O2 -std=c++11 test.cpp -o test.out -qno-opt-dynamic-align
clang: error: unknown argument: '-qno-opt-dynamic-align'
c++ -fPIC -Wall -O2 -std=c++11 test.cpp -o test.out -Werror -Wno-missing-field-initializers
c++ -fPIC -Wall -O2 -std=c++11 -Wno-missing-field-initializers test.cpp -o test.out -Werror -Wno-cast-function-type
    **** Trying the options provided by python3.9-config --ldflags ****
    **** Trying the following options for linking against Python library ****
c++ -fPIC -Wall -O2 -std=c++11 -Wno-missing-field-initializers -Wno-cast-function-type test.cpp -o ./agamatest.so -I"/Users/pauramos/miniconda3/envs/python3_agama/include/python3.9" -I"/Users/pauramos/miniconda3/envs/python3_agama/lib/python3.9/site-packages/numpy/core/include" -shared -fPIC -L/Users/pauramos/miniconda3/envs/python3_agama/lib/python3.9/config-3.9-darwin -ldl -framework CoreFoundation
Undefined symbols for architecture arm64:
  "_PyCapsule_GetPointer", referenced from:
      _PyInit_agamatest in test-90ec7c.o
  "_PyCapsule_Type", referenced from:
      _PyInit_agamatest in test-90ec7c.o
  "_PyErr_Format", referenced from:
      _PyInit_agamatest in test-90ec7c.o
  "_PyErr_Print", referenced from:
      _PyInit_agamatest in test-90ec7c.o
  "_PyErr_SetString", referenced from:
      _PyInit_agamatest in test-90ec7c.o
  "_PyExc_AttributeError", referenced from:
      _PyInit_agamatest in test-90ec7c.o
  "_PyExc_ImportError", referenced from:
      _PyInit_agamatest in test-90ec7c.o
  "_PyExc_RuntimeError", referenced from:
      _PyInit_agamatest in test-90ec7c.o
  "_PyImport_ImportModule", referenced from:
      _PyInit_agamatest in test-90ec7c.o
  "_PyModule_Create2", referenced from:
      _PyInit_agamatest in test-90ec7c.o
  "_PyObject_GetAttrString", referenced from:
      _PyInit_agamatest in test-90ec7c.o
  "_PyRun_SimpleStringFlags", referenced from:
      bla() in test-90ec7c.o
      run() in test-90ec7c.o
      _PyInit_agamatest in test-90ec7c.o
  "_Py_Finalize", referenced from:
      run() in test-90ec7c.o
  "_Py_Initialize", referenced from:
      run() in test-90ec7c.o
  "__Py_Dealloc", referenced from:
      _PyInit_agamatest in test-90ec7c.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: Could not compile test program which uses libpython3.9

I do think the problem is that Xcode does not support OpenMP now. Then, reading the error I realised that the code can be compiled with GCC, but since I set '--yes' I did not get to change the compiler. I will try again without this before trying to install a second Clang compiler with brew.

**Comment by brugalada** [comment] 2022-04-18 15:12
Ok, so it would seem like the system's Clang does not have the file omp.h (or, at least, I cannot find it). I do have an omp.h file in the Clang compiler installed within the conda environment, but I guess Agama is taking by default the Xcode compiler.

**Comment by brugalada** [comment] 2022-04-18 15:51
Just to be thorough, I tried installing llvm package, which includes clang, with homebrew. Then added those paths to the zshrc file.

Now the compilation stops at the same place but the error I get is slightly different:

> /opt/homebrew/opt/llvm/bin/clang++ -I /opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 test.cpp -o test.out 
/opt/homebrew/opt/llvm/bin/clang++ -I /opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 test.cpp -o test.out -fopenmp -Werror -Wno-unknown-pragmas
ld: library not found for -lomp
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
/opt/homebrew/opt/llvm/bin/clang++ -I /opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 test.cpp -o test.out -lgomp -Xpreprocessor -fopenmp -Werror -Wno-unknown-pragmas
ld: library not found for -lgomp
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
/opt/homebrew/opt/llvm/bin/clang++ -I /opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 test.cpp -o test.out -lomp -Xpreprocessor -fopenmp -Werror -Wno-unknown-pragmas
ld: library not found for -lomp
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
Warning, OpenMP is not supported
If you're compiling on MacOS with clang, you'd better install another compiler such as GCC
Do you want to continue without OpenMP? [Y/N] n


So I guess I have something wrong with my paths, although I do specify the following:
`export LDFLAGS="-L /opt/homebrew/lib -L/opt/homebrew/opt/llvm/lib"`

**Comment by eugvas** [comment] 2022-04-18 16:36
hi Pau,
I believe the original error is not related to OpenMP: after all, the library can be compiled without it, although of course it will be slower.
The problem seems to be in the incompatible architectures in Anaconda's Python (which still uses x86-64 as in all previous Intel-based Mac's) and the native ARM64 instruction set that GCC and CLANG are compiling to.
Even though MacOS on M1 can run x86-64 code by dynamically translating it on the fly to ARM64 (that's why anaconda still works), it seems impossible to mix the two architectures at the level of Python modules. And oddly, clang from Xcode is *not* able to compile to x86-64 code anymore (hence the error "the clang compiler does not support '-march=core2'") - I wonder if the one from Homebrew is more versatile.
The best solution is to replace "anaconda", which is currently only available in the x86-64 version, by "miniconda", which is available in the ARM64 version; then Agama should be compiled to native code without problems. Unfortunately, this also means that you would need to reinstall all other anaconda packages - but at least the native versions should run faster.
As to why clang from homebrew is still failing to find OpenMP: first, can you verify that libomp.so or libgomp.so are present in the folders you specified with LDFLAGS. If yes, then the problem is likely that these flags are not provided to the compiler (this seems to be a bug in the installation script) - can you replace `join(CXXFLAGS)` in line 141 of setup.py by `join(CXXFLAGS+LINK_FLAGS)` and run it once again?

**Comment by brugalada** [comment] 2022-04-19 14:36
Done. Everything the same until the part of compiling GSL. There are several warnings but I got to the next milestone: now I'm prompted to download Eigen, which works. Afterwards, though, it failed to install CVXOPT: `Command '['/Users/pauramos/miniconda3/envs/python_agama/bin/python', '-m', 'pip', 'install', '--user', 'cvxopt']' returned non-zero exit status 1.`

I continue to download the other modules. And it finished. I open a new terminal, and try to import agama, which works. I will try to run my python code and see if everything works but, for now, I'd call this a success jeje

**Comment by brugalada** [comment] 2022-04-19 14:42
Just for completeness, I attach the full log of the installation.

[agama_installation_arm64_python3.8.txt](https://github.com/GalacticDynamics-Oxford/Agama/files/8513974/agama_installation_arm64_python3.8.txt)

**Comment by brugalada** [comment] 2022-04-19 14:46
Everything seems to be working fine so far... So, in the end, installing llvm and libomp via homebrew seemed to solve it (after writing the paths correctly). 

What do you think, Eugene? Do you think it looks good?

**Comment by eugvas** [comment] 2022-04-19 14:54
ah well, so it works! but in the end you chose to compile without OpenMP support.
why don't you try to rerun the setup script after editing the line 141 as I described earlier and setting the correct `LDFLAGS=-L/opt/homebrew/lib` ?
CVXOPT failed to install because a pre-built binary is not available for ARM64, and compilation from source is basically impossible (for some reason, the source code no longer includes a critical third-party component, UMFPACK, which would need to be installed manually.. so forget it, since I guess you're not going to use the Schwarzschild modelling module anyway).

**Comment by brugalada** [comment] 2022-04-19 18:08
If I do that, seems like OpenMP is found but then I get this other error:

>     ==== Checking supported compiler options and available libraries ====
> 
> /opt/homebrew/opt/llvm/bin/clang++ -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 -L/opt/homebrew/lib -L/opt/homebrew/opt/llvm/lib test.cpp -o test.out 
> /opt/homebrew/opt/llvm/bin/clang++ -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 -L/opt/homebrew/lib -L/opt/homebrew/opt/llvm/lib test.cpp -o test.out -fopenmp -Werror -Wno-unknown-pragmas
> /opt/homebrew/opt/llvm/bin/clang++ -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 -fopenmp -L/opt/homebrew/lib -L/opt/homebrew/opt/llvm/lib test.cpp -o test.out -std=c++11
> /opt/homebrew/opt/llvm/bin/clang++ -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 -fopenmp -std=c++11 -L/opt/homebrew/lib -L/opt/homebrew/opt/llvm/lib test.cpp -o test.out -march=native
> clang-13: error: the clang compiler does not support '-march=native'
> /opt/homebrew/opt/llvm/bin/clang++ -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 -fopenmp -std=c++11 -L/opt/homebrew/lib -L/opt/homebrew/opt/llvm/lib test.cpp -o test.out -march=core2
> clang-13: error: the clang compiler does not support '-march=core2'
> /opt/homebrew/opt/llvm/bin/clang++ -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 -fopenmp -std=c++11 -L/opt/homebrew/lib -L/opt/homebrew/opt/llvm/lib test.cpp -o test.out -qno-opt-dynamic-align
> clang-13: error: unknown argument: '-qno-opt-dynamic-align'
> /opt/homebrew/opt/llvm/bin/clang++ -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 -fopenmp -std=c++11 -L/opt/homebrew/lib -L/opt/homebrew/opt/llvm/lib test.cpp -o test.out -Werror -Wno-missing-field-initializers
> /opt/homebrew/opt/llvm/bin/clang++ -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 -fopenmp -std=c++11 -Wno-missing-field-initializers -L/opt/homebrew/lib -L/opt/homebrew/opt/llvm/lib test.cpp -o test.out -Werror -Wno-cast-function-type
>     **** Trying the options provided by python3.9-config --ldflags ****
>     **** Trying the following options for linking against Python library ****
> /opt/homebrew/opt/llvm/bin/clang++ -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 -fopenmp -std=c++11 -Wno-missing-field-initializers -Wno-cast-function-type -L/opt/homebrew/lib -L/opt/homebrew/opt/llvm/lib test.cpp -o ./agamatest.so -I"/Users/pauramos/miniconda3/envs/python3_agama/include/python3.9" -I"/Users/pauramos/miniconda3/envs/python3_agama/lib/python3.9/site-packages/numpy/core/include" -shared -fPIC -L/Users/pauramos/miniconda3/envs/python3_agama/lib/python3.9/config-3.9-darwin -ldl -framework CoreFoundation
> Undefined symbols for architecture arm64:
>   "_PyCapsule_GetPointer", referenced from:
>       _PyInit_agamatest in test-ab74bf.o
>   "_PyCapsule_Type", referenced from:
>       _PyInit_agamatest in test-ab74bf.o
>   "_PyErr_Format", referenced from:
>       _PyInit_agamatest in test-ab74bf.o
>   "_PyErr_Print", referenced from:
>       _PyInit_agamatest in test-ab74bf.o
>   "_PyErr_SetString", referenced from:
>       _PyInit_agamatest in test-ab74bf.o
>   "_PyExc_AttributeError", referenced from:
>       _PyInit_agamatest in test-ab74bf.o
>   "_PyExc_ImportError", referenced from:
>       _PyInit_agamatest in test-ab74bf.o
>   "_PyExc_RuntimeError", referenced from:
>       _PyInit_agamatest in test-ab74bf.o
>   "_PyImport_ImportModule", referenced from:
>       _PyInit_agamatest in test-ab74bf.o
>   "_PyModule_Create2", referenced from:
>       _PyInit_agamatest in test-ab74bf.o
>   "_PyObject_GetAttrString", referenced from:
>       _PyInit_agamatest in test-ab74bf.o
>   "_PyRun_SimpleStringFlags", referenced from:
>       bla() in test-ab74bf.o
>       run() in test-ab74bf.o
>       _PyInit_agamatest in test-ab74bf.o
>   "_Py_Finalize", referenced from:
>       run() in test-ab74bf.o
>   "_Py_Initialize", referenced from:
>       run() in test-ab74bf.o
>   "__Py_Dealloc", referenced from:
>       _PyInit_agamatest in test-ab74bf.o
> ld: symbol(s) not found for architecture arm64
> clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
> error: Could not compile test program which uses libpython3.9

I'm not sure what can I do here from my part.

**Comment by eugvas** [comment] 2022-04-19 18:52
yeah, but that's the error you got originally when running Anaconda x86-64 Python 3.9; the one from Miniconda should be Python 3.8 for ARM - double check how you run setup.py!

**Comment by brugalada** [comment] 2022-04-20 09:54
Hi again,

I created a new conda environment with python 3.8, modified lined 141 of the setup.py file as you said and ran it again. It seemed to work (I was downloading GSL, Eigen, etc.) but it exited with a clang error when trying to compile the C++ libraries:

```
/opt/homebrew/opt/llvm/bin/clang++ -o "exe/test_math_core.exe" "tests/test_math_core.cpp" -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -fPIC -Wall -O2 -fopenmp -std=c++11 -Wno-missing-field-initializers -Wno-cast-function-type -Isrc agama.so -Wl,-rpath,/Users/pauramos/miniconda3/envs/python38_agama/lib /Users/pauramos/miniconda3/envs/python38_agama/lib/libpython3.8.dylib
ld: library not found for -lomp
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [exe/test_math_core.exe] Error 1
error: Compilation failed
```

I don't know much about these things but it seems weird that it failed here when similar calls have been executed without a problem up to this point in the installation. The only difference I can spot (I'm probably wrong) is that this is a call on an .exe file. I might be doing something obviously wrong but can't quite put my finger on it.

Also, just to be clear, all the tries I have done have been with the same miniconda. The only differences I can spot are the following:
- Python 3.9 (didn't work) vs Python 3.8 (worked without OpenMP)
- The Python 3.9 env was cloned from my general purpose env, while the 3.8 was a clean installation.

**Comment by eugvas** [comment] 2022-04-20 10:11
I see, so this path to the homebrew library folder also needs to be provided for compiling executable programs, not only the shared library.
At this point, `agama.so` should be already compiled successfully and with OpenMP support, so that's all you need for Python. However, for completeness, you may wish to compile the other test and example programs (some of them are actually quite useful!)
First try adding the path `-L/opt/homebrew/lib` to EXE_FLAGS in `Makefile.local` created by the setup script, then run `make`.
If that's successful, then can you also try editing the setup script as follows, and then re-running it from scratch:
after line 135, `EXE_FLAGS = []`, add the following:
``` 
   for LINK_FLAG in LINK_FLAGS:
        if LINK_FLAG.startswith('-L'): EXE_FLAGS.append(LINK_FLAG)
```
thanks!

**Comment by eugvas** [comment] 2022-04-21 08:08
also, it occurred to me that `clang` on M1 should actually be able to compile x86-64 code, if we ask it in a proper way. 
try going to line 230 of setup.py and replacing `ARCH_FLAG='-march=core2'` with `-arch x86_64` or perhaps `-march x86_64`, then running the *original* anaconda python (the one that is based on x86_64, not ARM architecture). If the first step (finding suitable compilation flags for the Python extension module) passes in this case, it will still fail later, when compiling GSL, since that step would also need to be modified in order to produce x86 code, but that's another story.
Nevertheless, compiling directly to native ARM instruction set is the preferred way, and hopefully some future versions of anaconda will support this out of the box.

**Comment by brugalada** [comment] 2022-04-21 08:25
I modified the Makefile.local and ran make as you said and it worked, no issue. 

Then I tried modifying the setup.py as you said and ran it again (on the same environment). Everything seemed to be working, went to all the section ==Compiling C++== but after that it checked *again* the supported compiler options. But this time it prompted my again with the question: `Warning, OpenMP is not supported
If you're compiling on MacOS with clang, you'd better install another compiler such as GCC
Do you want to continue without OpenMP?`

So I erased the Agama folder, cloned it again, modified setup.py (lines 135 and 141, created a new clean conda env, and ran the whole thing from scratch. I reached the same point. This time I said to try and continue without OpenMP. As I suspected, is doing the whole thing again since now is asking me to Download GSL, Eigen and the lot... again. This time, when it reached the end it said:

> No eggs found in /var/folders/vj/7jqz0m1j2zs3t7fxnl0d1gfw0000gn/T/easy_install-qfha_e9c/agama-1.0/egg-dist-tmp-7_ukcw7n (setup script problem?)
> error: The 'agama==1.0' distribution was not found and is required by the application
>

**Comment by eugvas** [comment] 2022-04-22 09:20
uhm, this left me thoroughly confused!.. 
but anyway, it seems that you managed to find a configuration where everything works as desired (with native ARM code and OpenMP support), so probably we can declare success.

**Comment by brugalada** [comment] 2022-04-22 09:23
I think so, yes jejeje When I have the time I will try and modify the line 230 of setup.py as suggested in one of your comments above :)

Thank you!

**Comment by eugvas** [comment] 2022-04-22 11:27
if you still have your Anaconda x86_64 installation, can you run the following piece of code in it, and then in the ARM64 Miniconda python (and possibly also in the system-default Python, whatever version it is), and report the results:

import platform,sys
print(platform.platform())
print(platform.uname()[3:])
print(sys.version())

I want to add a diagnostic message to the setup script that suggests to install a native ARM python version, but I need to be able to detect this condition reliably.

**Comment by brugalada** [comment] 2022-04-23 09:50
Sure!

Default:
> macOS-12.3.1-arm64-arm-64bit
> ('Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000', 'arm64', 'arm')
> 3.8.11 (default, Jul 29 2021, 14:57:32) 
> [Clang 12.0.0 ]


Python 3.9 (the one that you refer to as Anaconda x86_64)
> macOS-12.3.1-arm64-arm-64bit
> ('Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000', 'arm64', 'arm')
> 3.9.11 (main, Mar 28 2022, 05:06:09) 
> [Clang 12.0.0 ]


Python 3.8 (where I successfully installed Agama)
> macOS-12.3.1-arm64-arm-64bit
> ('Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000', 'arm64', 'arm')
> 3.8.13 (default, Mar 28 2022, 06:13:39) 
> [Clang 12.0.0 ]


The only difference I can see is in the sys.version which I guess is related to the Python version?

**Comment by eugvas** [comment] 2022-04-23 22:27
well, things are muddled as always!.. I hoped that the Anaconda x86_64 version would reveal itself in some way, but no luck.. anyway, thanks!

**Comment by eugvas** [comment] 2022-07-24 16:35
I made further modifications in the setup script that should hopefully be able to determine correct compilation flags for either ARM or x86_64 architectures on the newer Mac systems (matching the architecture of the Python interpreter itself). Will keep this thread open for further success or failure stories..

**Comment by eugvas** [comment] 2024-06-10 00:50
finally I got to test the installation procedures on an Apple ARM system, and it seems to work fine in all configurations (arm64 vs x86_64, native Python or Anaconda, etc.). So I am closing this ticket as completed.

**Closed by eugvas** 2024-06-10 00:50 UTC
